'use client'

import { createContext, useContext, useEffect, useState } from 'react'

type Language = 'en' | 'fr' | 'es' | 'de' | 'pt' | 'rw'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Navigation
    home: 'Home',
    mergePdf: 'Merge PDF',
    splitPdf: 'Split PDF',
    compressPdf: 'Compress PDF',
    rotatePdf: 'Rotate PDF',
    pdfToJpg: 'PDF to JPG',
    pdfToPng: 'PDF to PNG',
    blog: 'Blog',
    about: 'About',
    contact: 'Contact',

    // Common
    loading: 'Loading...',
    processing: 'Processing...',
    completed: 'Completed',
    error: 'Error',
    upload: 'Upload',
    download: 'Download',
    reset: 'Reset',
    close: 'Close',
    next: 'Next',
    previous: 'Previous',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    apply: 'Apply',
    clear: 'Clear',

    // Tool descriptions
    mergePdfDesc: 'Combine multiple PDF files into one document instantly',
    splitPdfDesc: 'Extract and split PDF pages into separate files',
    compressPdfDesc: 'Reduce PDF file size while maintaining quality',
    rotatePdfDesc: 'Rotate PDF pages 90, 180, or 270 degrees',
    pdfToJpgDesc: 'Convert PDF pages to high-quality JPG images',
    pdfToPngDesc: 'Convert PDF pages to PNG images with transparency',

    // Stats
    filesProcessed: 'Files Processed',
    trustedUsers: 'Trusted Users',
    averageRating: 'Average Rating',
    reviews: 'Reviews',

    // Trust indicators
    secure: 'Secure & Private',
    noRegistration: 'No Registration Required',
    clientSide: 'Client-Side Processing',
    free: '100% Free',

    // Footer
    company: 'UsePDF',
    description: 'Fast, private, and free PDF tools. No signup required.',
    quickLinks: 'Quick Links',
    tools: 'Tools',
    support: 'Support',
    legal: 'Legal',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    cookies: 'Cookie Policy',
    contactUs: 'Contact Us',
    followUs: 'Follow Us',
    copyright: '© 2024 UsePDF. All rights reserved.',

    // Reviews
    customerReviews: 'Customer Reviews',
    writeReview: 'Write a Review',
    rating: 'Rating',
    review: 'Review',
    submit: 'Submit',
    verifiedUser: 'Verified User',
    helpful: 'Helpful',
    report: 'Report',

    // Dark mode
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    system: 'System',

    // Languages
    english: 'English',
    french: 'Français',
    spanish: 'Español',
    german: 'Deutsch',
    portuguese: 'Português',
    kinyarwanda: 'Kinyarwanda',
  },
  fr: {
    home: 'Accueil',
    mergePdf: 'Fusionner PDF',
    splitPdf: 'Diviser PDF',
    compressPdf: 'Compresser PDF',
    rotatePdf: 'Pivoter PDF',
    pdfToJpg: 'PDF vers JPG',
    pdfToPng: 'PDF vers PNG',
    blog: 'Blog',
    about: 'À propos',
    contact: 'Contact',
    loading: 'Chargement...',
    processing: 'Traitement...',
    completed: 'Terminé',
    error: 'Erreur',
    upload: 'Téléverser',
    download: 'Télécharger',
    reset: 'Réinitialiser',
    close: 'Fermer',
    next: 'Suivant',
    previous: 'Précédent',
    cancel: 'Annuler',
    save: 'Enregistrer',
    delete: 'Supprimer',
    edit: 'Modifier',
    view: 'Voir',
    search: 'Rechercher',
    filter: 'Filtrer',
    sort: 'Trier',
    apply: 'Appliquer',
    clear: 'Effacer',
    mergePdfDesc: 'Combiner plusieurs fichiers PDF en un seul document instantanément',
    splitPdfDesc: 'Extraire et diviser les pages PDF en fichiers séparés',
    compressPdfDesc: 'Réduire la taille des fichiers PDF tout en conservant la qualité',
    rotatePdfDesc: 'Pivoter les pages PDF de 90, 180 ou 270 degrés',
    pdfToJpgDesc: 'Convertir les pages PDF en images JPG de haute qualité',
    pdfToPngDesc: 'Convertir les pages PDF en images PNG avec transparence',
    filesProcessed: 'Fichiers traités',
    trustedUsers: 'Utilisateurs de confiance',
    averageRating: 'Note moyenne',
    reviews: 'Avis',
    secure: 'Sécurisé et privé',
    noRegistration: 'Aucune inscription requise',
    clientSide: 'Traitement côté client',
    free: '100% gratuit',
    company: 'UsePDF',
    description: 'Outils PDF rapides, privés et gratuits. Aucune inscription requise.',
    quickLinks: 'Liens rapides',
    tools: 'Outils',
    support: 'Support',
    legal: 'Légal',
    privacy: 'Politique de confidentialité',
    terms: 'Conditions d\'utilisation',
    cookies: 'Politique des cookies',
    contactUs: 'Nous contacter',
    followUs: 'Suivez-nous',
    copyright: '© 2024 UsePDF. Tous droits réservés.',
    customerReviews: 'Avis clients',
    writeReview: 'Écrire un avis',
    rating: 'Note',
    review: 'Avis',
    submit: 'Soumettre',
    verifiedUser: 'Utilisateur vérifié',
    helpful: 'Utile',
    report: 'Signaler',
    lightMode: 'Mode clair',
    darkMode: 'Mode sombre',
    system: 'Système',
    english: 'English',
    french: 'Français',
    spanish: 'Español',
    german: 'Deutsch',
    portuguese: 'Português',
    kinyarwanda: 'Kinyarwanda',
  },
  es: {
    home: 'Inicio',
    mergePdf: 'Combinar PDF',
    splitPdf: 'Dividir PDF',
    compressPdf: 'Comprimir PDF',
    rotatePdf: 'Rotar PDF',
    pdfToJpg: 'PDF a JPG',
    pdfToPng: 'PDF a PNG',
    blog: 'Blog',
    about: 'Acerca de',
    contact: 'Contacto',
    loading: 'Cargando...',
    processing: 'Procesando...',
    completed: 'Completado',
    error: 'Error',
    upload: 'Subir',
    download: 'Descargar',
    reset: 'Reiniciar',
    close: 'Cerrar',
    next: 'Siguiente',
    previous: 'Anterior',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    view: 'Ver',
    search: 'Buscar',
    filter: 'Filtrar',
    sort: 'Ordenar',
    apply: 'Aplicar',
    clear: 'Limpiar',
    mergePdfDesc: 'Combina múltiples archivos PDF en un solo documento al instante',
    splitPdfDesc: 'Extrae y divide las páginas PDF en archivos separados',
    compressPdfDesc: 'Reduce el tamaño de los archivos PDF manteniendo la calidad',
    rotatePdfDesc: 'Rota las páginas PDF 90, 180 o 270 grados',
    pdfToJpgDesc: 'Convierte páginas PDF a imágenes JPG de alta calidad',
    pdfToPngDesc: 'Convierte páginas PDF a imágenes PNG con transparencia',
    filesProcessed: 'Archivos procesados',
    trustedUsers: 'Usuarios de confianza',
    averageRating: 'Calificación promedio',
    reviews: 'Reseñas',
    secure: 'Seguro y privado',
    noRegistration: 'Sin registro requerido',
    clientSide: 'Procesamiento del lado del cliente',
    free: '100% gratis',
    company: 'UsePDF',
    description: 'Herramientas PDF rápidas, privadas y gratuitas. Sin registro requerido.',
    quickLinks: 'Enlaces rápidos',
    tools: 'Herramientas',
    support: 'Soporte',
    legal: 'Legal',
    privacy: 'Política de privacidad',
    terms: 'Términos de servicio',
    cookies: 'Política de cookies',
    contactUs: 'Contáctanos',
    followUs: 'Síguenos',
    copyright: '© 2024 UsePDF. Todos los derechos reservados.',
    customerReviews: 'Reseñas de clientes',
    writeReview: 'Escribir una reseña',
    rating: 'Calificación',
    review: 'Reseña',
    submit: 'Enviar',
    verifiedUser: 'Usuario verificado',
    helpful: 'Útil',
    report: 'Reportar',
    lightMode: 'Modo claro',
    darkMode: 'Modo oscuro',
    system: 'Sistema',
    english: 'English',
    french: 'Français',
    spanish: 'Español',
    german: 'Deutsch',
    portuguese: 'Português',
    kinyarwanda: 'Kinyarwanda',
  },
  de: {
    home: 'Startseite',
    mergePdf: 'PDF zusammenführen',
    splitPdf: 'PDF teilen',
    compressPdf: 'PDF komprimieren',
    rotatePdf: 'PDF drehen',
    pdfToJpg: 'PDF zu JPG',
    pdfToPng: 'PDF zu PNG',
    blog: 'Blog',
    about: 'Über uns',
    contact: 'Kontakt',
    loading: 'Laden...',
    processing: 'Verarbeitung...',
    completed: 'Abgeschlossen',
    error: 'Fehler',
    upload: 'Hochladen',
    download: 'Herunterladen',
    reset: 'Zurücksetzen',
    close: 'Schließen',
    next: 'Weiter',
    previous: 'Zurück',
    cancel: 'Abbrechen',
    save: 'Speichern',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    view: 'Ansehen',
    search: 'Suchen',
    filter: 'Filtern',
    sort: 'Sortieren',
    apply: 'Anwenden',
    clear: 'Löschen',
    mergePdfDesc: 'Mehrere PDF-Dateien sofort zu einem Dokument zusammenführen',
    splitPdfDesc: 'PDF-Seiten extrahieren und in separate Dateien aufteilen',
    compressPdfDesc: 'PDF-Dateigröße reduzieren und Qualität beibehalten',
    rotatePdfDesc: 'PDF-Seiten um 90, 180 oder 270 Grad drehen',
    pdfToJpgDesc: 'PDF-Seiten in hochqualitative JPG-Bilder konvertieren',
    pdfToPngDesc: 'PDF-Seiten in PNG-Bilder mit Transparenz konvertieren',
    filesProcessed: 'Verarbeitete Dateien',
    trustedUsers: 'Vertrauenswürdige Benutzer',
    averageRating: 'Durchschnittliche Bewertung',
    reviews: 'Bewertungen',
    secure: 'Sicher und privat',
    noRegistration: 'Keine Registrierung erforderlich',
    clientSide: 'Client-seitige Verarbeitung',
    free: '100% kostenlos',
    company: 'UsePDF',
    description: 'Schnelle, private und kostenlose PDF-Tools. Keine Anmeldung erforderlich.',
    quickLinks: 'Schnelllinks',
    tools: 'Tools',
    support: 'Support',
    legal: 'Rechtliches',
    privacy: 'Datenschutzrichtlinie',
    terms: 'Nutzungsbedingungen',
    cookies: 'Cookie-Richtlinie',
    contactUs: 'Kontaktieren Sie uns',
    followUs: 'Folgen Sie uns',
    copyright: '© 2024 UsePDF. Alle Rechte vorbehalten.',
    customerReviews: 'Kundenbewertungen',
    writeReview: 'Eine Bewertung schreiben',
    rating: 'Bewertung',
    review: 'Bewertung',
    submit: 'Absenden',
    verifiedUser: 'Verifizierter Benutzer',
    helpful: 'Hilfreich',
    report: 'Melden',
    lightMode: 'Hellmodus',
    darkMode: 'Dunkelmodus',
    system: 'System',
    english: 'English',
    french: 'Français',
    spanish: 'Español',
    german: 'Deutsch',
    portuguese: 'Português',
    kinyarwanda: 'Kinyarwanda',
  },
  pt: {
    home: 'Início',
    mergePdf: 'Mesclar PDF',
    splitPdf: 'Dividir PDF',
    compressPdf: 'Comprimir PDF',
    rotatePdf: 'Girar PDF',
    pdfToJpg: 'PDF para JPG',
    pdfToPng: 'PDF para PNG',
    blog: 'Blog',
    about: 'Sobre',
    contact: 'Contato',
    loading: 'Carregando...',
    processing: 'Processando...',
    completed: 'Concluído',
    error: 'Erro',
    upload: 'Enviar',
    download: 'Baixar',
    reset: 'Redefinir',
    close: 'Fechar',
    next: 'Próximo',
    previous: 'Anterior',
    cancel: 'Cancelar',
    save: 'Salvar',
    delete: 'Excluir',
    edit: 'Editar',
    view: 'Visualizar',
    search: 'Pesquisar',
    filter: 'Filtrar',
    sort: 'Ordenar',
    apply: 'Aplicar',
    clear: 'Limpar',
    mergePdfDesc: 'Combine vários arquivos PDF em um único documento instantaneamente',
    splitPdfDesc: 'Extraia e divida páginas PDF em arquivos separados',
    compressPdfDesc: 'Reduza o tamanho dos arquivos PDF mantendo a qualidade',
    rotatePdfDesc: 'Gire páginas PDF em 90, 180 ou 270 graus',
    pdfToJpgDesc: 'Converta páginas PDF para imagens JPG de alta qualidade',
    pdfToPngDesc: 'Converta páginas PDF para imagens PNG com transparência',
    filesProcessed: 'Arquivos processados',
    trustedUsers: 'Usuários confiáveis',
    averageRating: 'Avaliação média',
    reviews: 'Avaliações',
    secure: 'Seguro e privado',
    noRegistration: 'Nenhum registro necessário',
    clientSide: 'Processamento do lado do cliente',
    free: '100% grátis',
    company: 'UsePDF',
    description: 'Ferramentas PDF rápidas, privadas e gratuitas. Nenhum cadastro necessário.',
    quickLinks: 'Links rápidos',
    tools: 'Ferramentas',
    support: 'Suporte',
    legal: 'Legal',
    privacy: 'Política de privacidade',
    terms: 'Termos de serviço',
    cookies: 'Política de cookies',
    contactUs: 'Entre em contato conosco',
    followUs: 'Siga-nos',
    copyright: '© 2024 UsePDF. Todos os direitos reservados.',
    customerReviews: 'Avaliações de clientes',
    writeReview: 'Escrever uma avaliação',
    rating: 'Avaliação',
    review: 'Avaliação',
    submit: 'Enviar',
    verifiedUser: 'Usuário verificado',
    helpful: 'Útil',
    report: 'Denunciar',
    lightMode: 'Modo claro',
    darkMode: 'Modo escuro',
    system: 'Sistema',
    english: 'English',
    french: 'Français',
    spanish: 'Español',
    german: 'Deutsch',
    portuguese: 'Português',
    kinyarwanda: 'Kinyarwanda',
  },
  rw: {
    home: 'Ahabanza',
    mergePdf: 'Gukomatanya PDF',
    splitPdf: 'Gucagagura PDF',
    compressPdf: 'Kugabanya PDF',
    rotatePdf: 'Guhindura PDF',
    pdfToJpg: 'PDF kuri JPG',
    pdfToPng: 'PDF kuri PNG',
    blog: 'Blog',
    about: 'Ibyerekeye',
    contact: 'Twandikire',
    loading: 'Birimo birimo...',
    processing: 'Birimo birakorwa...',
    completed: 'Byarangiye',
    error: 'Ikosa',
    upload: 'Shyira hejuru',
    download: 'Manura',
    reset: 'Ongera utangire',
    close: 'Funga',
    next: 'Ibikurikira',
    previous: 'Ibisanzwe',
    cancel: 'Hagarika',
    save: 'Bika',
    delete: 'Siba',
    edit: 'Hindura',
    view: 'Reba',
    search: 'Shakisha',
    filter: 'Hitamo',
    sort: 'Ihindurangano',
    apply: 'Koresha',
    clear: 'Siba',
    mergePdfDesc: 'Gukomatanya amadosiye menshi ya PDF mu idosiye imwe vuba',
    splitPdfDesc: 'Gukuramo no gucagagura amapaji ya PDF mu madosiye atandukanye',
    compressPdfDesc: 'Kugabanya ingano ya dosiye ya PDF ukomeza ubuziranenge',
    rotatePdfDesc: 'Guhindura amapaji ya PDF mu myerekezo ya 90, 180 cyangwa 270',
    pdfToJpgDesc: 'Guhindura amapaji ya PDF mu nshusho za JPG zifite ubuziranenge bwiza',
    pdfToPngDesc: 'Guhindura amapaji ya PDF mu nshusho za PNG zifite ubwerurutsi',
    filesProcessed: 'Amadosiye yakozwe',
    trustedUsers: 'Abakoresha batizerwa',
    averageRating: 'Icyiciro cy\'umwanya',
    reviews: 'Ibisobanuro',
    secure: 'Bikomeye kandi byibanga',
    noRegistration: 'Nta kwiyandikisha bisabwa',
    clientSide: 'Gukora ku ruhande rw\'umukoresha',
    free: '100% ubuntu',
    company: 'UsePDF',
    description: 'Ibikoresho bya PDF byihuta, byibanga kandi ubuntu. Nta kwiyandikisha bisabwa.',
    quickLinks: 'Amahuza yihuta',
    tools: 'Ibikoresho',
    support: 'Ubufasha',
    legal: 'Amategeko',
    privacy: 'Itegeko ry\'ibanga',
    terms: 'Amategeko yo gukoresha',
    cookies: 'Itegeko rya cookies',
    contactUs: 'Twandikire',
    followUs: 'Dukurikire',
    copyright: '© 2024 UsePDF. Uburenganzira bwose burabitswe.',
    customerReviews: 'Ibisobanuro by\'abakiliya',
    writeReview: 'Andika igisobanuro',
    rating: 'Icyiciro',
    review: 'Igisobanuro',
    submit: 'Ohereza',
    verifiedUser: 'Umukoresha yemejwe',
    helpful: 'Bifasha',
    report: 'Tanga raporo',
    lightMode: 'Uburyo bw\'umucyo',
    darkMode: 'Uburyo bw\'umwijima',
    system: 'Sisitemu',
    english: 'English',
    french: 'Français',
    spanish: 'Español',
    german: 'Deutsch',
    portuguese: 'Português',
    kinyarwanda: 'Kinyarwanda',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  useEffect(() => {
    // Load language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key
  }

  const setLanguageAndSave = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: setLanguageAndSave, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
